### ISSUE TITLE
Variants are inaccessible

### ISSUE THREAD

**Issue by RobbieGM** [niklasf/shakmaty#35]
Hi,
I am unable to instantiate a new `shakmaty::variant::Crazyhouse` since the module seems to be private. I'm not sure if this is related to one of the recent changes you made a few hours ago or if I am doing something wrong (I am new to Rust, forgive me). The docs say nothing about how to create variant positions and make moves on them, so I tried this:
```rust
use shakmaty::variant::Crazyhouse;
```
However, the `variant` module seems to be private. I have enabled the feature by including
```toml
[features]
variant = []
```
in my Cargo.toml file, so I don't see why I get the error `unresolved import 'shakmaty::variant' could not find 'variant' in 'shakmaty'`. What I'm trying to do is just create a basic crazyhouse board and make some moves on it, like I can with the example in the docs for standard chess.

**Comment by niklasf** [comment]
Hi. Enabling variants should work like that:

```toml
[dependencies]
shakmaty = { version = "0.18", features = ["variant"] }
```
